### ISSUE TITLE
isOpen is not a function in SerialPort v5, but a property

### ISSUE THREAD

**Issue by juliendorra** [cotejp/hpgl#3]
Bug : when using node HPGL with the last version of node SerialPort, I got this error:
```
return (this.transport && this.transport.isOpen()) === true;
TypeError: this.transport.isOpen is not a function
```
Apparently "isOpen is now a property", starting from version 5.
https://github.com/node-serialport/node-serialport/blob/master/UPGRADE_GUIDE.md

Turning the function call into a property check on line 856 and 963 of hpgl.js fix the issue.

**Comment by djipco** [comment]
This has been fixed in version [0.8.7-5](https://github.com/cotejp/hpgl/releases/tag/0.8.7-5). This new version has been pushed to npm.
